# pigpio/Dockerfile.template
FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:bullseye

# Install pigpio daemon and a shell
RUN install_packages pigpio bash && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY start.sh .
RUN chmod +x start.sh

CMD ["bash", "-lc", "./start.sh"]
